# Exploring the Raw Data

In [ ]:
import pandas as pd
df = pd.read_csv("../data/raw/blood_lead.csv")

## Blood lead data

In [ ]:
df = pd.read_csv("../data/raw/blood_lead.csv")
df.shape

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.isna().sum()

### Extra Rows
Two rows aren't real neighborhoods: #0 is the citywide total, and #99 is "unknown".

In [ ]:
 df[df["community_area_name"].isin(["Chicago", "Unknown"])]

### Zero screenings 
A screening count of 0 likely means missing data, not that no kids were tested.

In [ ]:
cols = ["screened_for_lead_in_1999", "screened_for_lead_in_2000", "screened_for_lead_in_2001",
        "screened_for_lead_in_2002", "screened_for_lead_in_2003"]
(df[cols] == 0).sum()

In [60]:
df[df["screened_for_lead_in_2003"] == 0][["community_area_number", "community_area_name", "screened_for_lead_in_2003", "percent_elevated_2003"]]

,community_area_number,community_area_name,screened_for_lead_in_2003,percent_elevated_2003
54,54,Riverdale,0,0.0

In [61]:
df.describe()

,community_area_number,screened_for_lead_in_1999,lead_screening_rate_1999,screening_rate_1999_lower_ci,screening_rate_1999_upper_ci,elevated_blood_lead_level_in_1999,percent_elevated_1999,percent_elevated_1999_lower_ci,percent_elevated_1999_upper_ci,screened_for_lead_in_2000,...,percent_elevated_2012_lower_ci,percent_elevated_2012_upper_ci,screened_for_lead_in_2013,lead_screening_rate_2013,lead_screening_rate_2013_lower_ci,lead_screening_rate_2013_upper_ci,elevated_blood_lead_level_in_2013,percent_elevated_2013,percent_elevated_2013_lower_ci,percent_elevated_2013_upper_ci
count,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,...,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000
mean,39.265823,2457.848101,269.878481,251.186076,288.729114,417.443038,12.710127,10.634177,14.639241,2584.962025,...,0.386076,1.487342,2561.379747,370.050633,351.088608,389.012658,19.113924,0.659494,0.230380,1.155696
std,23.521245,10842.868473,120.137545,116.711588,124.146638,1853.633340,9.925008,9.634206,10.553216,11443.134812,...,0.473594,1.582303,11289.149504,127.432627,124.719397,130.809265,84.799611,0.561481,0.301855,1.004190
min,0.000000,67.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,81.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.500000,329.000000,182.400000,159.600000,200.600000,24.500000,5.750000,3.450000,7.550000,360.000000,...,0.000000,0.700000,538.500000,296.500000,273.500000,318.000000,1.000000,0.250000,0.000000,0.600000
50%,39.000000,1027.000000,277.100000,257.400000,293.500000,87.000000,9.900000,8.200000,11.900000,938.000000,...,0.200000,1.200000,1052.000000,372.000000,350.000000,404.000000,6.000000,0.600000,0.100000,1.000000
75%,58.500000,1821.000000,342.750000,325.200000,360.300000,352.500000,17.350000,15.450000,20.100000,1905.000000,...,0.600000,2.000000,1735.500000,484.500000,464.000000,502.500000,13.500000,0.900000,0.400000,1.500000
max,99.000000,97085.000000,565.600000,490.900000,640.300000,16489.000000,39.500000,37.000000,46.000000,102106.000000,...,2.100000,10.300000,101184.000000,571.000000,552.000000,633.000000,755.000000,2.800000,1.200000,5.700000